"""Add cloudinary_public_id to jobseeker and employer

Revision ID: 5626c6d6b348
Revises: 0a096304966a
Create Date: 2026-01-26 21:22:55.639864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5626c6d6b348'
down_revision: Union[str, Sequence[str], None] = '0a096304966a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.add_column('job_seekers', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_seekers', 'cloudinary_public_id')
    op.drop_column('employers', 'cloudinary_public_id')
    # ### end Alembic commands ###
