"""add_hiring_policy_ats_threshold_and_round_tracking

Revision ID: 04ec23d7367e
Revises: 2f11480cfbb0
Create Date: 2026-03-08 05:48:14.073929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04ec23d7367e'
down_revision: Union[str, Sequence[str], None] = '2f11480cfbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('ats_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Add current_round as nullable first, populate, then set NOT NULL
    op.add_column('applications', sa.Column('current_round', sa.Integer(), nullable=True))
    op.execute("UPDATE applications SET current_round = 0")
    op.alter_column('applications', 'current_round', nullable=False)
    
    op.add_column('jobs', sa.Column('hiring_policy', sa.Text(), nullable=True))
    # Add ats_threshold as nullable first, populate, then set NOT NULL
    op.add_column('jobs', sa.Column('ats_threshold', sa.Integer(), nullable=True))
    op.execute("UPDATE jobs SET ats_threshold = 0")
    op.alter_column('jobs', 'ats_threshold', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ats_threshold')
    op.drop_column('jobs', 'hiring_policy')
    op.drop_column('applications', 'current_round')
    op.drop_column('applications', 'ats_report')
    op.drop_column('applications', 'ats_score')
    # ### end Alembic commands ###
