"""Add saved_cover_letters table

Revision ID: 0a096304966a
Revises: 1db026021340
Create Date: 2026-01-26 21:15:59.860866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a096304966a'
down_revision: Union[str, Sequence[str], None] = '1db026021340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_cover_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jobseeker_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['job_seekers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='False only if account is suspended by admin, not during registration',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='False only if account is suspended by admin, not during registration',
               existing_nullable=False)
    op.drop_table('saved_cover_letters')
    # ### end Alembic commands ###
