"""add oauth and email verification fields to users

Revision ID: 1237006bd22b
Revises: 1854e5d25dd9
Create Date: 2025-12-26 11:40:05.333938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1237006bd22b'
down_revision: Union[str, Sequence[str], None] = '1854e5d25dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        'users',
        sa.Column('is_email_verified', sa.Boolean(), nullable=True)
    )

    # 2. Set default value for existing rows
    op.execute(
        "UPDATE users SET is_email_verified = FALSE"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        'users',
        'is_email_verified',
        nullable=False
    )

    # OAuth fields (safe to add directly)
    op.add_column(
        'users',
        sa.Column('oauth_provider', sa.String(), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('oauth_provider_id', sa.String(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('JOB_SEEKER', 'EMPLOYER', 'ADMIN', name='user_role_enum'),
               type_=postgresql.ENUM('JOB_SEEKER', 'EMPLOYER', 'ADMIN', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
