"""add_has_requested_slots_field

Revision ID: 219d818e6638
Revises: f49b072d5406
Create Date: 2026-03-09 15:53:53.503107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219d818e6638'
down_revision: Union[str, Sequence[str], None] = 'f49b072d5406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('has_requested_extra_slots', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'has_requested_extra_slots')
    # ### end Alembic commands ###
