"""modified for foreign keys

Revision ID: 22cb1de388b3
Revises: 45ff141cd270
Create Date: 2026-01-18 01:41:18.769441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22cb1de388b3'
down_revision: Union[str, Sequence[str], None] = '45ff141cd270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    op.drop_table('job_seekers')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('idx_job_created_at'), table_name='jobs')
    op.drop_index(op.f('idx_job_is_active'), table_name='jobs')
    op.drop_index(op.f('idx_job_location'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('employers')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email_verification_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verification_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.create_table('employers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Name of person managing this account'),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='e.g., HR Manager, Recruiter, CTO'),
    sa.Column('work_email', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Official work email (@company.com)'),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=True, comment='General company contact email'),
    sa.Column('company_website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_size', sa.VARCHAR(), autoincrement=False, nullable=True, comment='1-10, 11-50, 51-200, 201-500, 500+'),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_tier', sa.VARCHAR(), autoincrement=False, nullable=False, comment='UNVERIFIED | EMAIL_VERIFIED | DOCUMENT_VERIFIED | FULLY_VERIFIED | REJECTED | SUSPENDED'),
    sa.Column('company_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='REGISTERED | STARTUP | FREELANCE | NGO | GOVERNMENT'),
    sa.Column('is_startup', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('startup_stage', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Idea | MVP | Early Revenue | Growth'),
    sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rjsc_registration_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trade_license_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tin_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Admin notes on verification'),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('alternative_verification_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternative_verification_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('document_ai_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('document_ai_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trust_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employers_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='employers_verified_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='employers_pkey'),
    sa.UniqueConstraint('rjsc_registration_number', name='employers_rjsc_registration_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name='employers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('work_email', name='employers_work_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_fresh_graduate_friendly', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('jobs_employer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_job_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('idx_job_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('idx_job_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('job_seekers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('professional_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inferred_industries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Industries parsed from resume'),
    sa.Column('primary_industry', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Most relevant industry from CV'),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('volunteer_experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='job_seekers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_seekers_pkey'),
    sa.UniqueConstraint('user_id', name='job_seekers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_seeker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cloudinary_public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parse_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='resume_parse_status_enum'), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['job_seekers.id'], name=op.f('resumes_job_seeker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    # ### end Alembic commands ###
