"""Add selection process and saved jobs models

Revision ID: 2f11480cfbb0
Revises: 5626c6d6b348
Create Date: 2026-03-07 11:04:06.964248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f11480cfbb0'
down_revision: Union[str, Sequence[str], None] = '5626c6d6b348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
