"""add 3-tier verification system

Revision ID: 45ff141cd270
Revises: 34d7dd6be854
Create Date: 2026-01-18 00:54:36.982808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45ff141cd270'
down_revision: Union[str, Sequence[str], None] = '34d7dd6be854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('resumes')
    op.execute("DROP TABLE IF EXISTS resumes CASCADE;")
    op.execute("DROP TABLE IF EXISTS job_seekers CASCADE;")
    op.execute("DROP TABLE IF EXISTS password_reset_tokens CASCADE;")
    # op.drop_table('job_seekers')
    # op.drop_table('password_reset_tokens')
    op.execute("DROP INDEX IF EXISTS idx_job_created_at;")
    op.execute("DROP INDEX IF EXISTS idx_job_is_active;")
    op.execute("DROP INDEX IF EXISTS idx_job_location;")

    op.execute("DROP TABLE IF EXISTS jobs CASCADE;")
    op.execute("DROP TABLE IF EXISTS employers CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employers_pkey'),
    sa.UniqueConstraint('company_email', name='employers_company_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name='employers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('job_seekers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('professional_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of education entries with institution, degree, field, year'),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of work experience with company, position, duration, description'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of technical and soft skills'),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of projects with title, description, technologies, links'),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of certifications with name, issuer, date, credential_id'),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of awards/achievements with title, issuer, date, description'),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of languages with name and proficiency level'),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of publications/papers with title, journal, date, link'),
    sa.Column('volunteer_experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of volunteer work with organization, role, duration, description'),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Other professional links (Behance, Dribbble, etc.)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='job_seekers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_seekers_pkey'),
    sa.UniqueConstraint('user_id', name='job_seekers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_fresh_graduate_friendly', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('jobs_employer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_job_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('idx_job_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('idx_job_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_seeker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cloudinary_public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parse_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='resume_parse_status_enum'), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['job_seekers.id'], name=op.f('resumes_job_seeker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    # ### end Alembic commands ###
