"""Add subscription model and job posting limits

Revision ID: 50325f7c49bc
Revises: 82f70cb4792c
Create Date: 2026-01-18 15:56:59.052176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50325f7c49bc'
down_revision: Union[str, Sequence[str], None] = '82f70cb4792c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('resumes')
    op.execute("DROP TABLE IF EXISTS resumes CASCADE;")
    op.execute("DROP TABLE IF EXISTS job_seekers CASCADE;")
    op.execute("DROP TABLE IF EXISTS password_reset_tokens CASCADE;")
    # op.drop_table('job_seekers')
    # op.drop_table('password_reset_tokens')
    op.execute("DROP INDEX IF EXISTS idx_job_created_at;")
    op.execute("DROP INDEX IF EXISTS idx_job_is_active;")
    op.execute("DROP INDEX IF EXISTS idx_job_location;")

    op.execute("DROP TABLE IF EXISTS jobs CASCADE;")
    op.execute("DROP TABLE IF EXISTS employers CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_startup', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('startup_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('founded_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rjsc_registration_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trade_license_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tin_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('alternative_verification_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alternative_verification_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('document_ai_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('document_ai_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trust_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='employers_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='employers_verified_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='employers_pkey'),
    sa.UniqueConstraint('rjsc_registration_number', name='employers_rjsc_registration_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name='employers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('work_email', name='employers_work_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('job_seekers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('professional_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inferred_industries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Industries parsed from resume'),
    sa.Column('primary_industry', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Most relevant industry from CV'),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('volunteer_experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='job_seekers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='job_seekers_pkey'),
    sa.UniqueConstraint('user_id', name='job_seekers_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_seeker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cloudinary_public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parse_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='resume_parse_status_enum'), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['job_seekers.id'], name=op.f('resumes_job_seeker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_fresh_graduate_friendly', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('jobs_employer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_job_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('idx_job_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('idx_job_created_at'), 'jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###
