"""add_slot_pool_seeker_style_choice_fields

Revision ID: 87a9f534825a
Revises: 9085b687a285
Create Date: 2026-03-08 15:46:25.673439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a9f534825a'
down_revision: Union[str, Sequence[str], None] = '9085b687a285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_slot_pool', sa.Column('allow_seeker_style_choice', sa.Boolean(), nullable=False))
    op.add_column('interview_slot_pool', sa.Column('available_styles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_slot_pool', 'available_styles')
    op.drop_column('interview_slot_pool', 'allow_seeker_style_choice')
    # ### end Alembic commands ###
