"""add_interview_review_and_selection_features

Revision ID: a31de623160d
Revises: 219d818e6638
Create Date: 2026-03-10 10:47:25.937008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a31de623160d'
down_revision: Union[str, Sequence[str], None] = '219d818e6638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check for existing table to avoid DuplicateTable error
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    # 1. Add columns to interview_schedules
    sched_cols = [c['name'] for c in inspector.get_columns('interview_schedules')]
    if 'is_completed' not in sched_cols:
        op.add_column('interview_schedules', sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    if 'completed_at' not in sched_cols:
        op.add_column('interview_schedules', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))

    # 2. Add columns to job_seekers
    js_cols = [c['name'] for c in inspector.get_columns('job_seekers')]
    if 'is_employed' not in js_cols:
        op.add_column('job_seekers', sa.Column('is_employed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    if 'current_job_id' not in js_cols:
        op.add_column('job_seekers', sa.Column('current_job_id', sa.UUID(), nullable=True))
    if 'current_employer_name' not in js_cols:
        op.add_column('job_seekers', sa.Column('current_employer_name', sa.String(), nullable=True))
    if 'hired_at' not in js_cols:
        op.add_column('job_seekers', sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True))
        op.create_foreign_key('fk_job_seeker_current_job', 'job_seekers', 'jobs', ['current_job_id'], ['id'], ondelete='SET NULL')

    # 3. Add columns to jobs
    job_cols = [c['name'] for c in inspector.get_columns('jobs')]
    if 'selection_announcement_date' not in job_cols:
        op.add_column('jobs', sa.Column('selection_announcement_date', sa.DateTime(timezone=True), nullable=True))
    if 'is_selection_announced' not in job_cols:
        op.add_column('jobs', sa.Column('is_selection_announced', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # 4. Handle interview_reviews table
    if 'interview_reviews' in tables:
        op.drop_table('interview_reviews')
        
    op.create_table('interview_reviews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('application_id', sa.UUID(), nullable=False),
        sa.Column('interview_id', sa.UUID(), nullable=False),
        sa.Column('employer_id', sa.UUID(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('overall_rating', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['interview_id'], ['interview_schedules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_reviews')
    op.drop_column('jobs', 'is_selection_announced')
    op.drop_column('jobs', 'selection_announcement_date')
    op.drop_constraint('fk_job_seeker_current_job', 'job_seekers', type_='foreignkey')
    op.drop_column('job_seekers', 'hired_at')
    op.drop_column('job_seekers', 'current_employer_name')
    op.drop_column('job_seekers', 'current_job_id')
    op.drop_column('job_seekers', 'is_employed')
    op.drop_column('interview_schedules', 'completed_at')
    op.drop_column('interview_schedules', 'is_completed')
    # ### end Alembic commands ###
