"""add_ats_score_to_applications

Revision ID: d5969b0663a6
Revises: 4fa9781755d2
Create Date: 2026-03-04 22:35:48.306579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5969b0663a6'
down_revision: Union[str, Sequence[str], None] = '4fa9781755d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('ats_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ats_report')
    op.drop_column('applications', 'ats_score')
    # ### end Alembic commands ###
