"""improve_interview_slots

Revision ID: f49b072d5406
Revises: 87a9f534825a
Create Date: 2026-03-09 11:52:59.018719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49b072d5406'
down_revision: Union[str, Sequence[str], None] = '87a9f534825a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('booked_slot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'applications', 'interview_slot_pool', ['booked_slot_id'], ['id'], ondelete='SET NULL')
    op.add_column('interview_slot_pool', sa.Column('capacity', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('interview_slot_pool_application_id_fkey'), 'interview_slot_pool', type_='foreignkey')
    op.drop_column('interview_slot_pool', 'is_booked')
    op.drop_column('interview_slot_pool', 'application_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_slot_pool', sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('interview_slot_pool', sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('interview_slot_pool_application_id_fkey'), 'interview_slot_pool', 'applications', ['application_id'], ['id'], ondelete='SET NULL')
    op.drop_column('interview_slot_pool', 'capacity')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'booked_slot_id')
    # ### end Alembic commands ###
