"""add notifications and saved jobs tables

Revision ID: f67e1055b288
Revises: 04ec23d7367e
Create Date: 2026-03-08 10:12:28.821125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67e1055b288'
down_revision: Union[str, Sequence[str], None] = '04ec23d7367e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_schedules', sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_schedules', 'actual_start_at')
    # ### end Alembic commands ###
