"""make interview_id nullable in interview_reviews

Revision ID: f6e03ae8a215
Revises: a31de623160d
Create Date: 2026-03-12 12:04:32.166455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e03ae8a215'
down_revision: Union[str, Sequence[str], None] = 'a31de623160d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_reviews', 'interview_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_reviews', 'interview_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
